- name: Use Prometheus role to configure Prometheus server for strictly metal
  hosts: localhost
  become: true
  vars:
    prometheus_global:
      scrape_interval: 3s

    prometheus_scrape_configs:
      - job_name: "metal"
        static_configs:
          - targets: ["localhost:8888"]
      - job_name: "node-exporter"
        static_configs:
          - targets: ["localhost:9100"]

    prometheus_config_flags_extra:
        web.enable-admin-api:
        web.enable-lifecycle:

  roles:
    - role: prometheus.prometheus.prometheus
      vars:
        roles_path: /root/.ansible/collections/ansible_collections/prometheus/prometheus/roles
